env:
  browser: true
extends:
  - "airbnb"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules: {}
settings: {
    react: {
        "version": "latest",
    },
}